"use client";

import { ShieldAlert, Microscope, UserCog, Stethoscope } from "lucide-react";

export default function DisclaimerPage() {
  const points = [
    {
      title: "Non-Diagnostic Classification",
      description: "DermAI is an Artificial Intelligence-based classification tool for pigmented skin lesions. It is categorized as an 'Educational Support System' and is not a medical device. It does not provide a definitive medical diagnosis.",
      icon: Microscope
    },
    {
      title: "Professional Consult Mandatory",
      description: "Users should never delay seeking medical advice, disregard medical advice, or discontinue medical treatment because of information generated by this platform. Always consult a board-certified dermatologist.",
      icon: Stethoscope
    },
    {
      title: "Model Limitations",
      description: "The EfficientNet-B7 model used here is trained on the HAM10000 dataset. While accurate within its training parameters, it may not account for rare conditions, varied skin tones, or complex comorbidities not represented in its training data.",
      icon: UserCog
    }
  ];

  return (
    <div className="container mx-auto max-w-4xl px-4 py-20">
      <div className="rounded-[40px] border border-accent-orange/20 bg-accent-orange/5 p-12 shadow-2xl backdrop-blur-md">
        <div className="flex flex-col items-center text-center mb-12">
          <div className="h-20 w-20 flex items-center justify-center rounded-3xl bg-accent-orange/10 mb-8 border border-accent-orange/20">
            <ShieldAlert className="h-10 w-10 text-accent-orange" />
          </div>
          <h1 className="text-4xl font-black text-white tracking-tight sm:text-5xl">Medical Disclaimer</h1>
          <p className="text-accent-orange/80 mt-6 text-lg max-w-2xl leading-relaxed font-medium">
            CRITICAL INFORMATION: Please read and understand the operational limits of DermAI.
          </p>
        </div>

        <div className="space-y-6">
          {points.map((point) => (
            <div key={point.title} className="rounded-3xl bg-white/[0.03] border border-white/5 p-8 transition-all hover:bg-white/[0.05]">
              <div className="flex gap-6">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-bg-secondary border border-border-subtle">
                  <point.icon className="h-6 w-6 text-text-muted" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-white mb-3">{point.title}</h3>
                  <p className="text-text-secondary leading-relaxed text-[15px]">
                    {point.description}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 p-6 rounded-2xl border border-accent-orange/30 bg-accent-orange/10 text-center">
            <p className="text-sm font-black uppercase tracking-widest text-accent-orange">
              By using this tool, you acknowledge that you understand its educational nature.
            </p>
        </div>
      </div>
    </div>
  );
}
