"use client";

import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { PredictionResponse } from "@/types/prediction";
import { format } from "date-fns";

export const generatePDF = async (
  elementId: string, 
  prediction: PredictionResponse, 
  caseId: string
) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#0a0a0a", // Match dashboard theme
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

    // Add Header
    pdf.setFillColor(10, 10, 10);
    pdf.rect(0, 0, 210, 30, "F");
    
    pdf.setTextColor(74, 222, 128); // accent-green
    pdf.setFontSize(22);
    pdf.setFont("helvetica", "bold");
    pdf.text("DermAI — Clinical Report", 15, 20);

    pdf.setTextColor(150, 150, 150);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text(`CASE_ID: ${caseId}`, 15, 26);
    pdf.text(`DATE: ${format(new Date(), "PPpp")}`, 150, 26);

    // Add Dashboard Snapshot
    pdf.addImage(imgData, "PNG", 10, 40, pdfWidth - 20, pdfHeight - 20);

    // Add Footer Disclaimer
    pdf.setTextColor(100, 100, 100);
    pdf.setFontSize(7);
    const disclaimer = [
      "NOTICE: This report is generated by an artificial intelligence diagnostic assistant.",
      "This is not a final medical diagnosis. All findings should be reviewed and verified",
      "by a board-certified dermatologist using clinical dermoscopy."
    ];
    disclaimer.forEach((line, i) => {
      pdf.text(line, 105, 275 + (i * 3), { align: "center" });
    });

    pdf.save(`DermAI_Report_${caseId}.pdf`);
  } catch (error) {
    console.error("PDF Generation failed:", error);
  }
};
